name: Build Docker Image CI

on:
  push: 
    tags:        
    - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: medudev/medu-backend
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.vars.outputs.tag }}
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
